### ISSUE TITLE
vl53l0_init() segura o programa em caso de falha

### ISSUE THREAD

**Issue by FelipeGdM** [ThundeRatz/STMSensors#1]
A *vl53l0_init()* fica segurando a execução do programa principal quando a inicialização acontece com algum erro. Seria interessante evitar q isso aconteça, colocar um timeout ou algo do gênero

**Comment by d-nery** [comment]
Isso é sabido, feito para evitar que o programa rode às cegas, se quiser tirar pra testar algo, é só tirar as funções `HAL_I2C_Master_Transmit` de dentro do while, dentro das funções `write*` no arquivo `vl53l0x.c`:

```c
// while(HAL_I2C_Master_Transmit(&hi2c1, address, (uint8_t*)(&bytes), 2, TIMEOUT) != HAL_OK);
HAL_I2C_Master_Transmit(&hi2c1, address, (uint8_t*)(&bytes), 2, TIMEOUT);
```
